name: Lint & Prettier

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  formatter:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ./next-ver/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn
      - name: Run Prettier
        run: yarn workspace next-ver prettier
      - name: Run Lint
        run: yarn workspace next-ver lint
